### ISSUE TITLE
Astronoby::IncompatibleArgumentsError

### ISSUE THREAD

**Issue by trevorturk** [rhannequin/astronoby#106]
### Description

Sometimes I'm getting `Astronoby::IncompatibleArgumentsError` exceptions and I'm not sure if I'm doing something incorrectly. 

### Reproduction Steps

```ruby
lat = 41.87
lon = -87.62
time = Time.parse("2024-11-12 00:00:00 CST -06:00")
moon = Astronoby::Moon.new(time: time)
observer ||= Astronoby::Observer.new(
  latitude: Astronoby::Angle.from_degrees(lat),
  longitude: Astronoby::Angle.from_degrees(lon)
)
moon.observation_events(observer: observer)
```

### Expected behavior

Returns without error.

### Actual behavior

Raises: 

```
Astronoby::IncompatibleArgumentsError Exception: Interpolation factor must be between 0 and 1, got 2.0099675128164844
```

### System configuration
**astronoby version**:  0.5.0
**ruby version**: 3.3.6

**Comment by rhannequin** [comment]
@trevorturk Just an update on this to tell you I had a look at this during the week. At the moment I haven't been able to spot the problem.

The author of the algorithm (Jean Meeus in _Astronomical Algorithms_) uses a method of interpolation to compute some values from a range when we know _equidistant_ values.
At some point, and only in some configuration, the algorithm produces a value which is opposed to the interpolation logic.

I'm taking this bug seriously as I'm aware it makes the library unreliable for this feature.
I'll try to put some more time and keep investigating in the coming days.
Sorry for the delay.

**Comment by rhannequin** [comment]
> I'm not sure if I'm doing something incorrectly.

You are not, I have been able to reproduce the bug.

**Comment by trevorturk** [comment]
No worries, I know you're busy! Thanks for your attention in any case, and I'm sorry I also don't have time to be much help beyond reporting issues! 🫣

**Comment by rhannequin** [comment]
Hopefully #111 should fix this issue. Here's your example with the fix:

```rb
time = Time.utc(2024, 11, 12)
utc_offset = "-06:00"

observer = Astronoby::Observer.new(
  latitude: Astronoby::Angle.from_degrees(41.87),
  longitude: Astronoby::Angle.from_degrees(-87.62),
  utc_offset: utc_offset
)

moon = Astronoby::Moon.new(time: time)
observation_events = moon.observation_events(observer: observer)

observation_events.rising_time.getlocal(utc_offset)
# => 2024-11-12 14:39:55 -0600
```
