### ISSUE TITLE
Compare Astronoby results with SunCalc and document results

### ISSUE THREAD

**Issue by rhannequin** [rhannequin/astronoby#113]
### Problem this feature will solve

Discover the current state of accuracy for Astronoby.

### Desired solution

Provide documentation to users so that they know if the library fits their needs.

## Alternatives considered

In #111 and #112, a script is mentioned to test many observer locations for each day of 2024 in order to spot bugs. The same method could be used to spot occurrences where Astronoby and the library [SunCalc](https://github.com/fishbrain/sun_calc) have a significant difference.

These differences could then be analyzed and compare with the [IMCCE](https://www.imcce.fr/), considered as the source of truth, in order to have an idea of how accurate Astronoby is on the Ruby ecosystem.

## Additional context

Data to consider:
- Sun coordinates
- Moon coordinates
- Sun rising, transit and setting times
- Moon rising, transit and setting times
- Moon's illuminated fraction

**Comment by trevorturk** [comment]
In case it's useful or interesting, here's a bit of code for the other libraries / APIs I've been testing out: https://gist.github.com/trevorturk/f21ca0a1676a5680925c3d32c2f2cc51

There's some cruft in the `get(:weekly)` method, you could replace with HTTParty etc. There's also this really strange `t` method which I'm using to adjust dates generated from libraries to better match the data I get from weather data sources. I think we chatted about this a bit in a different issue, and it's... complicated 😬 

In any case, just skimming the code may be interesting to see how I'm trying to fetch the same data points from different libraries, including SunCalc, which I found was the other reasonable alternative to Astronoby.
